### ISSUE TITLE
Feature Cardinality

### ISSUE THREAD

**Issue by lothran** [Universal-Variability-Language/uvl-lsp#1]
Currently, feature cardinality is ignored and always set to 1. Enabling them for single features is trivial, but some questions about nested cardinalities remain.
- How do they interact with references to other trees that may have a different cardinality?
- Interactions with alternative and range subgroups.
- Are cardinalities inherited?

**Comment by pascalfoerster** [comment]
Code syntax with a,b in N, 0 <= a  <= n <= b. n is the number of true instances of parent:
```
parent cardinality [a..b] {Attribute}
    child
```
Rules: 
- Constraints apply to all parent instances and can't be specific to one instance.
- Attributes gets multiplied by n.

z3:
For z3 we decided to generate parent b times as a boolean and also generate children for each instance.
We check with `Atleast`, that at least a instances of parent are true.

When using Group cardinality this allows the instances of parent to count into the group cardinality counter.
If this is not a wanted behavior by the user, the user can put this feature inside a container (see alternative container).
This implementation also forces the user to put a feature with cardinality inside a "container" when using `alternative` to count as one:
```
alternative
    featureA
    container
        mandatory
            parent cardinality [a..b] {Attribute}
                child
    featureC
```
