### ISSUE TITLE
Bug in UVLS Configure window when using integers

### ISSUE THREAD

**Issue by kbryonkuleuven** [Universal-Variability-Language/uvl-lsp#108]
When I'm using an integer as a configuration parameter, the SAT function does not work correctly. 

For example: in my model, the CylinderArea can only be: 
![image](https://github.com/Universal-Variability-Language/uvl-lsp/assets/149393013/286b013d-76b1-4433-8914-47f3693d5dca)

When I fill in the integer (using my keypad) in the configuration window, it gives an error:
![image](https://github.com/Universal-Variability-Language/uvl-lsp/assets/149393013/1abaa1fa-07ee-4294-9687-49fd33a34766)

When I increase the number (using the arrows), it seems correct:
![image](https://github.com/Universal-Variability-Language/uvl-lsp/assets/149393013/7078c434-20eb-42c8-9c2a-6f844d0c0d94)

When I decrease again, it is still correct:
![image](https://github.com/Universal-Variability-Language/uvl-lsp/assets/149393013/13a0015e-55a2-44b6-bef2-c40b3cb90ce3)

Could it be that the solver uses the previous value, instead of the current one? And when you use the keypad, the solver uses only the first value you filled in, eg:

When I fill in "25", it only checks the "2".

* I'm running this in VSCode on Windows

Thanks!

**Comment by SundermannC** [comment]
Thanks a lot for the report @kbryonkuleuven. We will look into this.

**Comment by ThiBruUU** [comment]
It looks as if the check is always shifted by one click when the integer is entered. If you enter 25, only 2 is checked, if you enter 256, 25 is checked and if you even enter 2567, it is processed as 256.
