### ISSUE TITLE
Collapse and Expand Icons are switched

### ISSUE THREAD

**Issue by Koenneker** [Universal-Variability-Language/uvl-lsp#135]
Hi,

I recently started using this extension and was a bit confused in the beginning.
<img src="https://github.com/user-attachments/assets/ab6499a8-4457-4f53-ad18-eee8747aebf8" width=40% height=40%>
When I saw this screen, I assumed that my file did not Parse correctly since none of the components showed up in (what I assumed) was the expanded list.
<img src="https://github.com/user-attachments/assets/5fce17da-c1dc-47c2-8bf6-581fddba78aa" width=40% height=40%>
When I clicked on it, the Icon switched to the "collapsed" Icon but content showed up.

This is inverse to how it is handled in the rest of VSCode, where ">" indicated collapsed sections and "v" indicates expanded ones.
<img src="https://github.com/user-attachments/assets/62a20f92-b9c7-4c88-9916-8cef10d1fcdf" width=40% height=40%>
<img src="https://github.com/user-attachments/assets/ff444177-8810-4843-9ad3-f5cd087e89e4" width=40% height=40%>

I've also taken a look at other software like MacOs Finder, Windows Explorer and the Gnome file Manager and the behavior seems to be universal.
<img src="https://github.com/user-attachments/assets/33414776-7c4e-4c36-a666-44c71f93f5d2" width=40% height=40%>
<img src="https://github.com/user-attachments/assets/54ece335-7cd8-41b8-bd14-fc264fea1a5f" width=40% height=40%>
<img src="https://github.com/user-attachments/assets/62a0c414-a1c1-43a1-91bb-f5d925554f01" width=40% height=40%>
<img src="https://github.com/user-attachments/assets/8342e10b-fdd5-4aa7-a9e2-663abcacfb4e" width=80% height=80%>

I did check for the corresponding lines of code and will enter a PR shortly.

Thanks for your efforts, it is a great time-saver!

**Comment by SundermannC** [comment]
Fixed with #136
