### ISSUE TITLE
Confusing example in settings for uvls path

### ISSUE THREAD

**Issue by mhusm** [Universal-Variability-Language/uvl-lsp#137]
I've tried to use the VS Code extension and struggled a bit with the settings. There is a setting called `Path` with a description:

> "Path to `uvls` executable. Example: `C:/uvls/target/release/uvls.exe`."

I noticed that I have to omit the `uvls.exe` part for it to work. It should only point to the folder, not the file.

**Comment by mhusm** [comment]
Ignore the issue. Upon restarting VS code, I got another error message that complained about the missing uvls.exe. I think my original problem was somehow related to z3.

**Comment by SundermannC** [comment]
Hi @mhusm, 
thanks a lot for your report. I am glad to hear that you could resolve the issue. Are you still having issues with z3 or are those also resolved?

**Comment by mhusm** [comment]
It works now, but I don't 100% know how I fixed it. Previously I had an error for the SAT state. I downloaded z3 and added it to the path, but that had no immediate effect. Maybe it took a reboot or restart of VS Code.
