### ISSUE TITLE
Optimize Anomaly (Core/Dead/False-Optional) Detection

### ISSUE THREAD

**Issue by SundermannC** [Universal-Variability-Language/uvl-lsp#15]
Currently, checking whether a feature is dead requires one Z3 call per feature. Especially for larger feature models, this can be very expensive. As first optimization, we should at least analyze the returned assignment/model by the z3 solver to reduce the number of candidates. In particular, each feature set to true cannot be a dead feature and each feature set to false cannot be a core feature. Post-processing each result of such Z3 call should vastly reduce the number of required calls.

**Comment by ThiBruUU** [comment]
It is currently not clear how to optimize this issue. If the information about the values ​​were saved to reduce z3 calls, it would require a lot of overhead and logic to save and load that information to validate data when the UVL changes

**Comment by SundermannC** [comment]
Consider the following example with 4 variables:
The void check returns one valid configuration:
{a,b,!c,!d} -> Here, we already know that a and b are no dead and c and d are no core features.
Now, lets check if a is core with SAT(FM & !a) which could result in:
{!a,b,c,d} -> From that configuration we know that a, c, and d are neither core nor dead.
Now, we only need a last check for b. Overall, we performed only 2 additional SAT calls instead of 2*4=8.

Storing information between changes of the UVL models is valuable but not needed for now.
After a change we could just start the same procedure as above with the initial SAT call for checking voidness.

Does this help?

**Comment by SundermannC** [comment]
Implemented in https://github.com/Universal-Variability-Language/uvl-lsp/blob/4aabd2b23ea92a3089ee2c4965c74cb9a1f54187/uvls/src/smt.rs#L201
