### ISSUE TITLE
Include rule checking

### ISSUE THREAD

**Issue by lothran** [Universal-Variability-Language/uvl-lsp#3]
Since Z3 supports all UVL language features, SAT and SMT levels are unnecessary. But for correctness, we should at least output a warning when expressions don't follow includes.

**Comment by TobiUUlm** [comment]
This includes a warning if the includes are not valid with the used operators.  
List of operations and their Language-Levels can be found [here](https://github.com/Universal-Variability-Language/Universal-Variability-Language.github.io#language-levels).  
For now we need to implement the following:  
- [ ] SAT Level
  - [ ] SAT Core: Level without any extension as seen above
  - [ ] Group Cardinality: Specify selecting [n..m] (between n and m) children parent-children relationships D
- [ ] SMT Level
  - [ ] SMT Core: Supports constraints over feature attributes with standard arithmetic operations (+,-,*,/,=,!=,>,<) 
  - [ ] Attribute aggregates: Simplifies specification of attribute constraints by allowing sum() and avg() aggregates
  - [ ] Feature Cardinality: A single feature can be selected between n and m times

Operators are always valid if either
- No include exists at all
- the major_language_level includes the `Any` sub_language_level

**Comment by TobiUUlm** [comment]
We've implemented this feature and here are some previews/screenshots of how it shows invalid includes:  
Some SMT-level has to be included
![2023-05-02 18_08_08-test uvl - uvl - Visual Studio Code](https://user-images.githubusercontent.com/131375895/235722986-9cf81574-fe5e-457c-8f69-cc55b2b83c26.png)  

SAT-level.group-cardinality has to be included
![2023-05-02 18_08_42-● test uvl - uvl - Visual Studio Code](https://user-images.githubusercontent.com/131375895/235723025-e738f1ef-cacf-4b59-8a06-0692363309dc.png)

.* includes work as well.

Possible improvements:
When Feature cardinality is used without corresponding include (`SMT-level.feature-cardinality`), it will show the Error for the feature. We don't know how we could push the error to 'cardinality'. You can see this issue in the second screenshot.

We will do a pull-request.
