### ISSUE TITLE
Rename Language Levels

### ISSUE THREAD

**Issue by SundermannC** [Universal-Variability-Language/uvl-lsp#31]
After further discussions with other researchers involved in the development of UVL, we decided to rename the language levels SAT and SMT. In particular, the names should be changed to the following:

* SAT -> Boolean
* SMT -> Arithmetic

**Comment by SundermannC** [comment]
We also discussed streamlining the names a bit.
In particular, the -level should me removed resulting in:
* Boolean (instead of Boolean-Level or SAT-Level)
* Numeric
* Type

**Comment by TobiUUlm** [comment]
We won't keep support for "X-Level".  
This change will break existing models if they use "SAT-Level", "SMT-Level" or "TYPE-Level".  
However, we still have no stable release yet. Therefore it should be somewhat fine.
