### ISSUE TITLE
Add Type-Levels to the Includes

### ISSUE THREAD

**Issue by SundermannC** [Universal-Variability-Language/uvl-lsp#4]
Currently, the new [type levels](https://github.com/Universal-Variability-Language/uvl-parser2.0/pull/12) are already usable in the LSP. However, they cannot be explicitly specified via includes as seen below.

```
  include
	TYPE-level
	TYPE-level.numeric-constraints
	TYPE-level.string-constraints 
```

**Comment by TobiUUlm** [comment]
@SundermannC We're about to implement the `TYPE-level` and show which features need `.numeric-constraints` or `.string-constraints` to be included.  
However, we don't know which features are contained in these includes. (`len(..)` function, comparison with strings, etc.)?


Please let us know which functions are reserved for `TYPE-level`s.  
Comments in the following example (or additional constraints, etc) should do it:  
```
namespace type_level

include
	TYPE-level
	TYPE-level.numeric-constraints
	TYPE-level.string-constraints

features
	some_feature
		mandatory
			String feature1 {type_level_value "tempval"}
			String feature
			Integer feature2 {type_level_value "5"}
				alternative
					feature3
					Real feature4
constraints
    feature1 == 'something'
    len(feature1) == len(feature) & feature2 > len(feature1)
    len(feature1) == 2
    len(feature1) == feature2
    feature2 > 6
    floor(feature2) == 5
    ceil(feature2) == 5
```

Furthermore, what is the `type_level_value` exactly? This does not seem to work in our current uvls implementation.

**Comment by SundermannC** [comment]
TYPE-level.numeric-constraints consists of:
* floor(name)
* ceil(name)

TYPE-level.string-constraints consists of any constraints that include string operations which should include:
* len(<string>)
* String comparsions e.g. feature1 == 'something'

The type_level_values are ordinary feature attributes that are used for conversion between levels in the uvl-parser2.0. We do not need explicit handling of them in the LSP for now.
