### ISSUE TITLE
highlighting dead,... Features under Windows

### ISSUE THREAD

**Issue by MartinMUU** [Universal-Variability-Language/uvl-lsp#51]
on my system is a bug with the syntax highlighting.
As shown in the picture the syntax is only underlined and not e.g. highlighted in red like intended.
Using Windows 10 and UVLs Versin 0.2.1

![grafik](https://github.com/Universal-Variability-Language/uvl-lsp/assets/131437974/3f187a32-bc11-4724-858a-1d5501c3184f)

**Comment by pascalfoerster** [comment]
Does the bug always occur or only when you restart the server in VScode with the appropriate command?

**Comment by MartinMUU** [comment]
The bug does always occur.
