### ISSUE TITLE
UVL icon

### ISSUE THREAD

**Issue by felixrieg** [Universal-Variability-Language/uvl-lsp#64]
Add icon UVL file in tree view

**Comment by MartinMUU** [comment]
Made some Examples.
For the Logo:
![UVLS-logo2](https://github.com/Universal-Variability-Language/uvl-lsp/assets/131437974/08e6d73b-87ae-4099-81b5-57d8ef61b090)
![UVLS-logo](https://github.com/Universal-Variability-Language/uvl-lsp/assets/131437974/645feceb-c031-4c50-bf03-8d1ee0973732)

And some proposals for the file-icon
![UVLS-Icon](https://github.com/Universal-Variability-Language/uvl-lsp/assets/131437974/aaedf01b-40b5-4a98-89a3-b889cf828016)
