### ISSUE TITLE
Non-Numeric Entries Are Always Considered as Zero in Sums

### ISSUE THREAD

**Issue by SundermannC** [Universal-Variability-Language/uvl-lsp#80]
When using the sum() function every input but numeric features/attributes is considered as zero. This includes: 

- Boolean/String features
- Non-numeric attributes
- Faulty references (see below)
![image](https://github.com/Universal-Variability-Language/uvl-lsp/assets/24757266/2c59e6a3-76b9-46d1-bacf-cdde543b0c19)

Everything but numeric features/attributes should probably result in an error indicating a wrong type or wrong reference.

**Comment by TobiUUlm** [comment]
Added a rather simple check in the transformer that tries to find an attribute (with correct type) with the same name as entered.
b1d7aec669f5e5a1260fc9929003f5bd999c9826

What I found:  
References to attributes in other files / imports don't work (I tested it with the current master).

**Comment by TobiUUlm** [comment]
This is an inefficient check (runs through all attributes and checks if the name and type matches the parameter for each aggregate function)  
This could be easily optimized by using a hashmap (name->type) for the attributes and checking in O(1) if the attribute name exists and is part of the accepted types.  
However, its currently part of `transform`, where the hashmap would not fit semantically. Maybe we can put it in the `ast.rs` file.

**Comment by TobiUUlm** [comment]
Another problem that occured:  
Do attributes need to have the same type when their name is equal?  
To show what i mean, is this following case allowed?  
<img alt="2023-10-13 08_56_45- Extension Development Host  imtest uvl - uvl - Visual Studio Code" src="https://github.com/Universal-Variability-Language/uvl-lsp/assets/131375895/df3eb000-27c1-4dc0-a58d-67229d09c872">
