### ISSUE TITLE
Error implicating imported features on core features

### ISSUE THREAD

**Issue by ThiBruUU** [Universal-Variability-Language/uvl-lsp#88]
While testing constraints, I encountered the following issue, but it only occurs in this particular configuration. See screenshots.

![import1UVL](https://github.com/Universal-Variability-Language/uvl-lsp/assets/131388839/eaff5e2b-b484-48a5-a09c-6c980e7fc329)
![smallUVL](https://github.com/Universal-Variability-Language/uvl-lsp/assets/131388839/dc2b9288-d6d7-4cf1-ba7b-ac63584db5ad)

Important: If other features are used on both import1-side and the other side, taut will not occur.

Maybe I'm stupid, but can one of you check this?

**Comment by MartinMUU** [comment]
It's the same for me. looks really weird.
![grafik](https://github.com/Universal-Variability-Language/uvl-lsp/assets/131437974/c4eedf32-62d0-4fb3-9534-4a50ba02839b)

**Comment by felixrieg** [comment]
Maybe solved by #94

**Comment by SundermannC** [comment]
Fixed by #94
