### ISSUE TITLE
Missing autocompletion options

### ISSUE THREAD

**Issue by MartinMUU** [Universal-Variability-Language/uvl-lsp#99]
When using the sum() operator there should maybe also be operations like < or > in the suggestions

![grafik](https://github.com/Universal-Variability-Language/uvl-lsp/assets/131437974/093b52dd-07ba-4cfc-a522-795d899669da)

**Comment by felixrieg** [comment]
Its in review: https://github.com/Universal-Variability-Language/uvl-lsp/pull/67
Its actually ready to merge

**Comment by SundermannC** [comment]
Fixed by #67
